var inventions = [/*{"INVENTION":"longbow","YEAR":1000,"INVENTOR":"","COUNTRY":"Wales","id":"WAL","Link":"http://www.edinformatics.com/inventions_inventors/longbow.htm"},
{"INVENTION":"magnetic compass","YEAR":1119,"INVENTOR":"","COUNTRY":"China","id":"CHN","Link":"http://www.edinformatics.com/inventions_inventors/magnetic_compass.htm"},
{"INVENTION":"mirror","YEAR":1200,"INVENTOR":"Venetians","COUNTRY":"Italy", "id":"ITA","Link":"http://www.edinformatics.com/inventions_inventors/mirror.htm"},
{"INVENTION":"torpedo","YEAR":1275,"INVENTOR":"Hasan al-Rammah","COUNTRY":"Egypt","Link":"https://en.wikipedia.org/wiki/Torpedo"},
{"INVENTION":"land mine","YEAR":1277,"INVENTOR":"Lou Qianxia","COUNTRY":"China","id":"CHN","Link":"https://en.wikipedia.org/wiki/Land_mine"},
{"INVENTION":"eyeglasses","YEAR":1286,"INVENTOR":"Salvino degli Armati or Alessandro di Spina","COUNTRY":"Italy", "id":"ITA","Link":"http://www.edinformatics.com/inventions_inventors/eyeglasses.htm"},
{"INVENTION":"printing press, movable type","YEAR":1439,"INVENTOR":"Johannes Gutenberg","COUNTRY":"Germany","id":"DEU","Link":"http://www.edinformatics.com/inventions_inventors/printing_press.htm"},
{"INVENTION":"toothbrush","YEAR":1498,"INVENTOR":"","COUNTRY":"China","id":"CHN","Link":"http://www.edinformatics.com/inventions_inventors/toothbrush.htm"},
{"INVENTION":"pocket watch","YEAR":1500,"INVENTOR":"Peter Henlein","COUNTRY":"Germany","id":"DEU","Link":"http://www.edinformatics.com/inventions_inventors/pocket_watch.htm"},
{"INVENTION":"pencil","YEAR":1565,"INVENTOR":"Conrad Gesner","COUNTRY":"Switzerland","id":"CHE","Link":"http://www.edinformatics.com/inventions_inventors/pencil.htm"},
{"INVENTION":"Gregorian calendar","YEAR":1582,"INVENTOR":"Pope Gregory XIII","COUNTRY":"Italy", "id":"ITA","Link":"http://www.edinformatics.com/inventions_inventors/calendar.htm"},
{"INVENTION":"toilet flush","YEAR":1591,"INVENTOR":"Sir John Harington","COUNTRY":"United Kingdom","id":"GBR","Link":"http://www.edinformatics.com/inventions_inventors/flush_toilet.htm"},
{"INVENTION":"thermometer","YEAR":1592,"INVENTOR":"Galileo","COUNTRY":"Italy", "id":"ITA","Link":"http://www.edinformatics.com/inventions_inventors/thermometer.htm"},
{"INVENTION":"wheelchair","YEAR":1592,"INVENTOR":"","COUNTRY":"Spain","Link":"http://www.edinformatics.com/inventions_inventors/wheelchair.htm"},
{"INVENTION":"optical telescope","YEAR":1608,"INVENTOR":"Hans Lippershey","COUNTRY":"Netherlands","id":"NLD","Link":"http://www.edinformatics.com/inventions_inventors/telescope.htm"},
{"INVENTION":"optical microscope","YEAR":1620,"INVENTOR":"Hans & Zacharias Jansen","COUNTRY":"Netherlands","id":"NLD","Link":"http://www.edinformatics.com/inventions_inventors/microscope.htm"},
{"INVENTION":"submarine","YEAR":1620,"INVENTOR":"Cornelis Drebbel","COUNTRY":"Netherlands","id":"NLD","Link":"http://www.edinformatics.com/inventions_inventors/submarine.htm"},
{"INVENTION":"barometer","YEAR":1643,"INVENTOR":"Evangelista Torricelli","COUNTRY":"Italy", "id":"ITA","Link":"http://www.edinformatics.com/inventions_inventors/barometer.htm"},
{"INVENTION":"pendulum clock","YEAR":1656,"INVENTOR":"Christiaan Huygens","COUNTRY":"Netherlands","id":"NLD","Link":"http://www.edinformatics.com/inventions_inventors/pendulum_clock.htm"},
{"INVENTION":"calculus","YEAR":1683,"INVENTOR":"Sir Isaac Newton and Gottfried Wilhelm Leibniz (invented separately)","COUNTRY":"United Kingdom, Germany","Link":"http://www.edinformatics.com/inventions_inventors/calculus.htm"},
{"INVENTION":"steam engine","YEAR":1698,"INVENTOR":"Thomas Savery","COUNTRY":"United Kingdom","id":"GBR","Link":"http://www.edinformatics.com/inventions_inventors/steam_engine.htm"},
{"INVENTION":"sunglasses","YEAR":1752,"INVENTOR":"James Ayscough","COUNTRY":"United Kingdom","id":"GBR","Link":"http://www.edinformatics.com/inventions_inventors/sunglasses.htm"},
{"INVENTION":"chronometer","YEAR":1762,"INVENTOR":"John Harrison","COUNTRY":"United Kingdom","id":"GBR","Link":"http://www.edinformatics.com/inventions_inventors/chronometer.htm"},
{"INVENTION":"roller skates","YEAR":1765,"INVENTOR":"Joseph Merlin","COUNTRY":"Belgium","id":"BEL","Link":"http://www.edinformatics.com/inventions_inventors/roller_skates.htm"},
{"INVENTION":"carbonated drinks","YEAR":1772,"INVENTOR":"Joseph Priestley","COUNTRY":"United Kingdom","id":"GBR","Link":"http://www.edinformatics.com/inventions_inventors/soft_drinks.htm"},
{"INVENTION":"threshing machine","YEAR":1778,"INVENTOR":"Andrew Meikle","COUNTRY":"Scotland","id":"SCO","Link":"http://www.edinformatics.com/inventions_inventors/threshing_machine.htm"},
{"INVENTION":"hot-air balloon","YEAR":1783,"INVENTOR":"Joseph & Étienne Montgolfier","COUNTRY":"France","id":"FRA","Link":"http://www.edinformatics.com/inventions_inventors/hot_air_balloon.htm"},
{"INVENTION":"bifocal lens","YEAR":1784,"INVENTOR":"Benjamin Franklin","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/bifocal.htm"},
{"INVENTION":"oil lamp","YEAR":1784,"INVENTOR":"Aimé Argand","COUNTRY":"Switzerland","id":"CHE","Link":"http://www.edinformatics.com/inventions_inventors/oil_lamp.htm"},
{"INVENTION":"shoelaces","YEAR":1790,"INVENTOR":"","COUNTRY":"United Kingdom","id":"GBR","Link":"http://www.edinformatics.com/inventions_inventors/shoelaces.htm"},
{"INVENTION":"guillotine","YEAR":1792,"INVENTOR":"Joseph-Ignace Guillotin","COUNTRY":"France","id":"FRA","Link":"http://www.edinformatics.com/inventions_inventors/guillotine.htm"},
{"INVENTION":"cotton gin","YEAR":1793,"INVENTOR":"Eli Whitney","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/cotton_gin.htm"},
{"INVENTION":"ball bearing","YEAR":1794,"INVENTOR":"Philip Vaughan","COUNTRY":"United Kingdom","id":"GBR","Link":"http://www.edinformatics.com/inventions_inventors/ball_bearing.htm"},
{"INVENTION":"metric system of measurement","YEAR":1795,"INVENTOR":"French Academy of Sciences","COUNTRY":"France","id":"FRA","Link":"http://www.edinformatics.com/inventions_inventors/metric_system.htm"},
{"INVENTION":"vaccination","YEAR":1796,"INVENTOR":"Edward Jenner","COUNTRY":"United Kingdom","id":"GBR","Link":"http://www.edinformatics.com/inventions_inventors/vaccination.htm"},
{"INVENTION":"parachute","YEAR":1797,"INVENTOR":"André-Jacques Garnerin","COUNTRY":"France","id":"FRA","Link":"http://www.edinformatics.com/inventions_inventors/parachute.htm"},
*/{"INVENTION":"battery","YEAR":1800,"INVENTOR":"Alessandro Volta","COUNTRY":"Italy", "id":"ITA","Link":"http://www.edinformatics.com/inventions_inventors/battery.htm"},
{"INVENTION":"steamboat","YEAR":1807,"INVENTOR":"Robert Fulton","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/steam_boat.htm"},
{"INVENTION":"Atomic theory","YEAR":1808,"INVENTOR":"John Dalton","COUNTRY":"United Kingdom","id":"GBR","Link":"https://en.wikipedia.org/wiki/Atomic_theory"},
{"INVENTION":"can food","YEAR":1809,"INVENTOR":"Nicolas Appert","COUNTRY":"France","id":"FRA","Link":"http://www.edinformatics.com/inventions_inventors/food_canning.htm"},
{"INVENTION":"American Sign Language","YEAR":1817,"INVENTOR":"Thomas H. Gallaudet","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/sign_language.htm"},
{"INVENTION":"bicycle","YEAR":1818,"INVENTOR":"Baron Karl de Drais de Sauerbrun","COUNTRY":"Germany","id":"DEU","Link":"http://www.edinformatics.com/inventions_inventors/bicycle.htm"},
{"INVENTION":"stethoscope","YEAR":1819,"INVENTOR":"René Laennec","COUNTRY":"France","id":"FRA","Link":"http://www.edinformatics.com/inventions_inventors/stethoscope.htm"},
{"INVENTION":"Fresnel lens","YEAR":1820,"INVENTOR":"Augustin-Jean Fresnel","COUNTRY":"France","id":"FRA","Link":"http://www.edinformatics.com/inventions_inventors/fresnel_lens.htm"},
{"INVENTION":"Programmable mechanical computer","YEAR":1822,"INVENTOR":"Charles Babbage","COUNTRY":"United Kingdom","id":"GBR","Link":"https://en.wikipedia.org/wiki/Mechanical_computer"},
{"INVENTION":"Braille system","YEAR":1824,"INVENTOR":"Louis Braille","COUNTRY":"France","id":"FRA","Link":"http://www.edinformatics.com/inventions_inventors/braille.htm"},
{"INVENTION":"cement","YEAR":1824,"INVENTOR":"Joseph Aspdin","COUNTRY":"United Kingdom","id":"GBR","Link":"http://www.edinformatics.com/inventions_inventors/cement.htm"},
{"INVENTION":"electromagnet","YEAR":1825,"INVENTOR":"William Sturgeon","COUNTRY":"United Kingdom","id":"GBR","Link":"https://en.wikipedia.org/wiki/Electromagnet"},
{"INVENTION":"gas stove","YEAR":1826,"INVENTOR":"James Sharp","COUNTRY":"United Kingdom","id":"GBR","Link":"http://www.edinformatics.com/inventions_inventors/gas_stove.htm"},
{"INVENTION":"matches","YEAR":1827,"INVENTOR":"John Walker","COUNTRY":"United Kingdom","id":"GBR","Link":"http://www.edinformatics.com/inventions_inventors/matches.htm"},
{"INVENTION":"locomotive","YEAR":1829,"INVENTOR":"George Stephenson","COUNTRY":"United Kingdom","id":"GBR","Link":"http://www.edinformatics.com/inventions_inventors/locomotive.htm"},
{"INVENTION":"elastic fabric","YEAR":1830,"INVENTOR":"Thomas Hancock","COUNTRY":"United Kingdom","id":"GBR","Link":""},
{"INVENTION":"thermostat","YEAR":1830,"INVENTOR":"Andrew Ure","COUNTRY":"United Kingdom","id":"GBR","Link":"http://www.edinformatics.com/inventions_inventors/thermostat.htm"},
{"INVENTION":"mechanical reaper","YEAR":1831,"INVENTOR":"Cyrus Hall McCormick","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/mechanical_reaper.htm"},
{"INVENTION":"telegraph","YEAR":1832,"INVENTOR":"Samuel F.B. Morse","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/telegraph.htm"},
{"INVENTION":"electric motor","YEAR":1834,"INVENTOR":"Thomas Davenport","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/electric_motors.htm"},
{"INVENTION":"revolver","YEAR":1835,"INVENTOR":"Samuel Colt","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/revolver.htm"},
{"INVENTION":"steel plow","YEAR":1836,"INVENTOR":"John Deere","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/steel_plow.htm"},
{"INVENTION":"photography","YEAR":1837,"INVENTOR":"Louis-Jacques-Mandé Daguerre","COUNTRY":"France","id":"FRA","Link":"http://www.edinformatics.com/inventions_inventors/photography.htm"},
{"INVENTION":"Morse code","YEAR":1838,"INVENTOR":"Samuel F.B. Morse","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/morse_code.htm"},
{"INVENTION":"fuel cell","YEAR":1839,"INVENTOR":"William R. Grove","COUNTRY":"United Kingdom","id":"GBR","Link":"http://www.edinformatics.com/inventions_inventors/fuel_cell.htm"},
{"INVENTION":"vulcanized rubber","YEAR":1839,"INVENTOR":"Charles Goodyear","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/rubber.htm"},
{"INVENTION":"postage stamps","YEAR":1840,"INVENTOR":"Sir Rowland Hill","COUNTRY":"United Kingdom","id":"GBR","Link":"http://www.edinformatics.com/inventions_inventors/postage_stamp.htm"},
{"INVENTION":"sewing machine","YEAR":1841,"INVENTOR":"Bartholemy Thimonnier","COUNTRY":"France","id":"FRA","Link":"http://www.edinformatics.com/inventions_inventors/sewing_machine.htm"},
{"INVENTION":"refrigerator","YEAR":1842,"INVENTOR":"John Gorrie","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/refrigerator.htm"},
{"INVENTION":"rubber band","YEAR":1845,"INVENTOR":"Stephen Perry","COUNTRY":"United Kingdom","id":"GBR","Link":"http://www.edinformatics.com/inventions_inventors/rubber_band.htm"},
{"INVENTION":"saxophone","YEAR":1846,"INVENTOR":"Antoine-Joseph Sax","COUNTRY":"Belgium","id":"BEL","Link":"http://www.edinformatics.com/inventions_inventors/saxophone.htm"},
{"INVENTION":"doughnut (ring) or donut","YEAR":1847,"INVENTOR":"Hanson Crockett Gregory","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/doughnuts.htm"},
{"INVENTION":"safety pin","YEAR":1849,"INVENTOR":"Walter Hunt","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/safety_pin.htm"},
{"INVENTION":"airship","YEAR":1852,"INVENTOR":"Henri Giffard","COUNTRY":"France","id":"FRA","Link":"http://www.edinformatics.com/inventions_inventors/airship.htm"},
{"INVENTION":"elevator","YEAR":1852,"INVENTOR":"Elisha Graves Otis","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/elevator.htm"},
{"INVENTION":"hypodermic syringe","YEAR":1853,"INVENTOR":"Charles Gabriel Pravaz","COUNTRY":"France","id":"FRA","Link":"http://www.edinformatics.com/inventions_inventors/hypodermic_syringe.htm"},
{"INVENTION":"potato chips","YEAR":1853,"INVENTOR":"George Crum","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/potato_chips.htm"},
{"INVENTION":"dry cleaning","YEAR":1855,"INVENTOR":"Jean Baptiste Jolly","COUNTRY":"France","id":"FRA","Link":"http://www.edinformatics.com/inventions_inventors/dry_cleaning.htm"},
{"INVENTION":"steel for mass-production","YEAR":1856,"INVENTOR":"Henry Bessemer","COUNTRY":"United Kingdom","id":"GBR","Link":"http://www.edinformatics.com/inventions_inventors/steel.htm"},
{"INVENTION":"tissue","YEAR":1857,"INVENTOR":"Joseph Gayetty","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/toilet_paper.htm"},
{"INVENTION":"can opener","YEAR":1858,"INVENTOR":"Ezra J. Warner","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/can_opener.htm"},
{"INVENTION":"engine with internal combustion","YEAR":1859,"INVENTOR":"Étienne Lenoir","COUNTRY":"France","id":"FRA","Link":"http://www.edinformatics.com/inventions_inventors/engines.htm"},
{"INVENTION":"oil well","YEAR":1859,"INVENTOR":"Edwin Laurentine Drake","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/oil_well.htm"},
{"INVENTION":"linoleum","YEAR":1860,"INVENTOR":"Frederick Walton","COUNTRY":"United Kingdom","id":"GBR","Link":"http://www.edinformatics.com/inventions_inventors/linoleum.htm"},
{"INVENTION":"pasteurization","YEAR":1864,"INVENTOR":"Louis Pasteur","COUNTRY":"France","id":"FRA","Link":"http://www.edinformatics.com/inventions_inventors/pasteurization.htm"},
{"INVENTION":"stapler","YEAR":1866,"INVENTOR":"George W. McGill","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/stapler.htm"},
{"INVENTION":"reinforced concrete","YEAR":1867,"INVENTOR":"Joseph Monier","COUNTRY":"France","id":"FRA","Link":"http://www.edinformatics.com/inventions_inventors/reinforced_concrete.htm"},
{"INVENTION":"dynamite","YEAR":1867,"INVENTOR":"Alfred Nobel","COUNTRY":"Sweden","id":"SWE","Link":"http://www.edinformatics.com/inventions_inventors/dynamite.htm"},
{"INVENTION":"stock ticker","YEAR":1867,"INVENTOR":"Edward A. Calahan","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/stock_ticker.htm"},
{"INVENTION":"typewriter","YEAR":1868,"INVENTOR":"Christopher Latham Sholes","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/typewriter.htm"},
{"INVENTION":"celluloid","YEAR":1869,"INVENTOR":"John Wesley Hyatt","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/celluloid.htm"},
{"INVENTION":"margarine","YEAR":1869,"INVENTOR":"Hippolyte Mège-Mouriès","COUNTRY":"France","id":"FRA","Link":"http://www.edinformatics.com/inventions_inventors/margarine.htm"},
{"INVENTION":"bag","YEAR":1870,"INVENTOR":"Margaret Knight","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/paper_bag.htm"},
{"INVENTION":"chewing gum (modern)","YEAR":1870,"INVENTOR":"Thomas Adams","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/chewing_gum.htm"},
{"INVENTION":"cardboard","YEAR":1871,"INVENTOR":"Albert Jones","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/cardboard.htm"},
{"INVENTION":"periodic table","YEAR":1871,"INVENTOR":"Dmitry Ivanovich Mendeleyev","COUNTRY":"Russia","id":"RUS","Link":"http://www.worldofmolecules.com/elements/"},
{"INVENTION":"catalog","YEAR":1872,"INVENTOR":"Aaron Montgomery Ward","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/mail_order_catalog.htm"},
{"INVENTION":"polyvinyl chloride (PVC)","YEAR":1872,"INVENTOR":"Eugen Baumann","COUNTRY":"Germany","id":"DEU","Link":"http://www.edinformatics.com/inventions_inventors/polyvinyl_chloride.htm"},
{"INVENTION":"jeans","YEAR":1873,"INVENTOR":"Levi Strauss, Jacob Davis","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/jeans.htm"},
{"INVENTION":"barbed wire","YEAR":1874,"INVENTOR":"Joseph Glidden","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/barbed_wire.htm"},
{"INVENTION":"DDT","YEAR":1874,"INVENTOR":"Othmar Zeidler","COUNTRY":"Germany","id":"DEU","Link":"http://www.worldofmolecules.com/pesticides/ddt.htm"},
{"INVENTION":"metal detector","YEAR":1874,"INVENTOR":"Gustave Trouvé","COUNTRY":"France","id":"FRA","Link":"http://www.edinformatics.com/inventions_inventors/metal_detector.htm"},
{"INVENTION":"telephone","YEAR":1876,"INVENTOR":"Alexander Graham Bell","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/telephone.htm"},
{"INVENTION":"phonograph","YEAR":1877,"INVENTOR":"Thomas Alva Edison","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/phonogaph.htm"},
{"INVENTION":"cream separator (dairy processing)","YEAR":1878,"INVENTOR":"Carl Gustaf Patrik de Laval","COUNTRY":"Sweden","id":"SWE","Link":"http://www.edinformatics.com/inventions_inventors/cream-separator.html"},
{"INVENTION":"microphone","YEAR":1878,"INVENTOR":"David E. Hughes","COUNTRY":"United Kingdom","id":"GBR","Link":"http://www.edinformatics.com/inventions_inventors/microphone.htm"},
{"INVENTION":"cathode rays","YEAR":1878,"INVENTOR":"William Crookes","COUNTRY":"United Kingdom","id":"GBR","Link":"https://en.wikipedia.org/wiki/Cathode_ray"},
{"INVENTION":"cash register","YEAR":1879,"INVENTOR":"James Ritty","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/cash_register.htm"},
{"INVENTION":"light bulb","YEAR":1879,"INVENTOR":"Thomas Alva Edison","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/incandescent_light_bulb.htm"},
{"INVENTION":"saccharin","YEAR":1879,"INVENTOR":"Ira Remsen, Constantin Fahlberg","COUNTRY":"Germany","id":"DEU","Link":"http://www.edinformatics.com/inventions_inventors/saccharin.htm"},
{"INVENTION":"film","YEAR":1884,"INVENTOR":"George Eastman","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/photographic_film.htm"},
{"INVENTION":"rayon","YEAR":1884,"INVENTOR":"Louis-Marie-Hilaire Bernigaud, count of Chardonnet","COUNTRY":"France","id":"FRA","Link":"http://www.edinformatics.com/inventions_inventors/rayon.htm"},
{"INVENTION":"roller coaster","YEAR":1884,"INVENTOR":"LeMarcus A. Thompson","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/roller_coaster.htm"},
{"INVENTION":"skyscraper","YEAR":1884,"INVENTOR":"William Le Baron Jenney","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/skyscrapers.htm"},
{"INVENTION":"motorcycle","YEAR":1885,"INVENTOR":"Gottlieb Daimler, Wilhelm Maybach","COUNTRY":"Germany","id":"DEU","Link":"http://www.edinformatics.com/inventions_inventors/motorcycle.htm"},
{"INVENTION":"dishwasher","YEAR":1886,"INVENTOR":"Josephine Cochrane","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/dishwasher.htm"},
{"INVENTION":"contact lenses","YEAR":1887,"INVENTOR":"Adolf Fick","COUNTRY":"Germany","id":"DEU","Link":"http://www.edinformatics.com/inventions_inventors/contact_lenses.htm"},
{"INVENTION":"camera","YEAR":1888,"INVENTOR":"George Eastman","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/camera.htm"},
{"INVENTION":"electric chair","YEAR":1888,"INVENTOR":"Harold P. Brown, Arthur E. Kennelly","COUNTRY":"United States of America","id":"USA","Link":""},
{"INVENTION":"straw","YEAR":1888,"INVENTOR":"Marvin Stone","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/drinking_straw.htm"},
{"INVENTION":"pneumatic tire","YEAR":1888,"INVENTOR":"John Boyd Dunlop","COUNTRY":"United Kingdom","id":"GBR","Link":"http://www.edinformatics.com/inventions_inventors/tire.htm"},
{"INVENTION":"automobile","YEAR":1889,"INVENTOR":"Gottlieb Daimler","COUNTRY":"Germany","id":"DEU","Link":"http://www.edinformatics.com/inventions_inventors/automobile.htm"},
{"INVENTION":"jukebox","YEAR":1889,"INVENTOR":"Louis Glass","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/jukebox.htm"},
{"INVENTION":"camera (motion picture)","YEAR":1891,"INVENTOR":"Thomas Alva Edison, William K.L. Dickson","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/movie_camera.htm"},
{"INVENTION":"escalator","YEAR":1891,"INVENTOR":"Jesse W. Reno","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/escalator.htm"},
{"INVENTION":"tractor","YEAR":1892,"INVENTOR":"John Froehlich","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/tractor.htm"},
{"INVENTION":"slot machine","YEAR":1893,"INVENTOR":"Charles Fey","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/slot_machine.htm"},
{"INVENTION":"toaster","YEAR":1893,"INVENTOR":"Crompton Co.","COUNTRY":"United Kingdom","id":"GBR","Link":"http://www.edinformatics.com/inventions_inventors/toaster.htm"},
{"INVENTION":"zipper","YEAR":1893,"INVENTOR":"Whitcomb L. Judson","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/zipper.htm"},
{"INVENTION":"cereal flakes","YEAR":1894,"INVENTOR":"John Harvey Kellogg","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/breakfast_cereal.htm"},
{"INVENTION":"X-ray imaging","YEAR":1895,"INVENTOR":"Wilhelm Conrad Räntgen","COUNTRY":"Germany","id":"DEU","Link":"http://www.edinformatics.com/inventions_inventors/x_ray_imaging.htm"},
{"INVENTION":"radio","YEAR":1896,"INVENTOR":"Guglielmo Marconi","COUNTRY":"Italy", "id":"ITA","Link":"http://www.edinformatics.com/inventions_inventors/radio.htm"},
{"INVENTION":"electric stove","YEAR":1896,"INVENTOR":"William Hadaway","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/electric_stove.htm"},
{"INVENTION":"aspirin","YEAR":1897,"INVENTOR":"Felix Hoffmann (Bayer)","COUNTRY":"Germany","id":"DEU","Link":"http://www.worldofmolecules.com/drugs/aspirin.htm"},
{"INVENTION":"JELL-O (gelatin dessert)","YEAR":1897,"INVENTOR":"Pearle B. Wait","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/jello.htm"},
{"INVENTION":"answering machine","YEAR":1898,"INVENTOR":"Valdemar Poulsen","COUNTRY":"Denmark","id":"DNK","Link":"http://www.edinformatics.com/inventions_inventors/answering_machine.htm"},
{"INVENTION":"battery-operated portable flashlight","YEAR":1899,"INVENTOR":"Conrad Hubert","COUNTRY":"Russia","id":"RUS","Link":"http://www.edinformatics.com/inventions_inventors/flashlight.htm"},
{"INVENTION":"paper clip","YEAR":1899,"INVENTOR":"Johan Vaaler","COUNTRY":"Norway","id":"NOR","Link":"http://www.edinformatics.com/inventions_inventors/paper_clip.htm"},
{"INVENTION":"razor","YEAR":1900,"INVENTOR":"King Camp Gillette","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/safety_razor.htm"},
{"INVENTION":"Old quantum theory","YEAR":1900,"INVENTOR":"Max Planck","COUNTRY":"Germany","id":"DEU","Link":"https://en.wikipedia.org/wiki/Old_quantum_theory"},
{"INVENTION":"vacuum cleaner","YEAR":1901,"INVENTOR":"Herbert Cecil Booth","COUNTRY":"United Kingdom","id":"GBR","Link":"http://www.edinformatics.com/inventions_inventors/vacuum_cleaner.htm"},
{"INVENTION":"air conditioning","YEAR":1902,"INVENTOR":"Willis Haviland Carrier","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/air_conditioning.htm"},
{"INVENTION":"teddy bear","YEAR":1902,"INVENTOR":"Morris Michtom","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/teddy_bear.htm"},
{"INVENTION":"gas turbine","YEAR":1903,"INVENTOR":"Jens William Ægidius Elling","COUNTRY":"Norway","id":"NOR","Link":"https://en.wikipedia.org/wiki/Gas_turbine"},
{"INVENTION":"engine-powered airplane","YEAR":1903,"INVENTOR":"Wilbur & Orville Wright","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/airplane.htm"},
{"INVENTION":"electrocardiogram (ECG, EKG)","YEAR":1903,"INVENTOR":"Willem Einthoven","COUNTRY":"Netherlands","id":"NLD","Link":"http://www.edinformatics.com/inventions_inventors/electrocardiogram.htm"},
{"INVENTION":"radar","YEAR":1904,"INVENTOR":"Christian Hälsmeyer","COUNTRY":"Germany","id":"DEU","Link":"http://www.edinformatics.com/inventions_inventors/radar.htm"},
{"INVENTION":"silicone","YEAR":1904,"INVENTOR":"Frederic Stanley Kipping","COUNTRY":"United Kingdom","id":"GBR","Link":"http://www.edinformatics.com/inventions_inventors/silicone.htm"},
{"INVENTION":"coffee (decaffeinated)","YEAR":1905,"INVENTOR":"Ludwig Roselius","COUNTRY":"Germany","id":"DEU","Link":"http://www.edinformatics.com/inventions_inventors/decaffeination.htm"},
{"INVENTION":"theory of relativity","YEAR":1905,"INVENTOR":"Albert Einstein","COUNTRY":"Germany","id":"DEU","Link":"https://en.wikipedia.org/wiki/Theory_of_relativity"},
{"INVENTION":"animation (motion-picture)","YEAR":1906,"INVENTOR":"J. Stuart Blackton","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/stop_motion_animation.htm"},
{"INVENTION":"bakelite","YEAR":1907,"INVENTOR":"Leo Hendrik Baekeland","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/bakelite.htm"},
{"INVENTION":"washing machine","YEAR":1907,"INVENTOR":"Alva J. Fisher","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/washing_machine.htm"},
{"INVENTION":"coffee (drip)","YEAR":1908,"INVENTOR":"Melitta Bentz","COUNTRY":"Germany","id":"DEU","Link":"http://www.edinformatics.com/inventions_inventors/drip_coffee.htm"},
{"INVENTION":"Geiger counter","YEAR":1908,"INVENTOR":"Hans Geiger","COUNTRY":"Germany","id":"DEU","Link":"http://www.edinformatics.com/inventions_inventors/geiger_counter.htm"},
{"INVENTION":"safety glass","YEAR":1909,"INVENTOR":"Édouard Bénédictus","COUNTRY":"France","id":"FRA","Link":"http://www.edinformatics.com/inventions_inventors/safety_glass.htm"},
{"INVENTION":"neon lighting","YEAR":1910,"INVENTOR":"Georges Claude","COUNTRY":"France","id":"FRA","Link":"http://www.edinformatics.com/inventions_inventors/neon_lamp.htm"},
{"INVENTION":"cellophane","YEAR":1911,"INVENTOR":"Jacques E. Brandenberger","COUNTRY":"Switzerland","id":"CHE","Link":"http://www.edinformatics.com/inventions_inventors/cellophane.htm"},
{"INVENTION":"tea bag","YEAR":1912,"INVENTOR":"Thomas Sullivan","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/tea_bag.htm"},
{"INVENTION":"assembly line","YEAR":1913,"INVENTOR":"Henry Ford","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/assembly_line.htm"},
{"INVENTION":"brassiere (bra)","YEAR":1913,"INVENTOR":"Mary Phelps Jacob","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/brassiere.htm"},
{"INVENTION":"crossword puzzles","YEAR":1913,"INVENTOR":"Arthur Wynne","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/crossword_puzzle.htm"},
{"INVENTION":"steel, stainless","YEAR":1914,"INVENTOR":"Harry Brearley","COUNTRY":"United Kingdom","id":"GBR","Link":"http://www.edinformatics.com/inventions_inventors/steel.htm"},
{"INVENTION":"lipstick tube","YEAR":1915,"INVENTOR":"Maurice Levy","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/lipstick.htm"},
{"INVENTION":"sonar","YEAR":1915,"INVENTOR":"Paul Langevin","COUNTRY":"France","id":"FRA","Link":"http://www.edinformatics.com/inventions_inventors/sonar.htm"},
{"INVENTION":"military tank","YEAR":1915,"INVENTOR":"Admiralty Landships Committee","COUNTRY":"United Kingdom","id":"GBR","Link":"http://www.edinformatics.com/inventions_inventors/military_tank.htm"},
{"INVENTION":"corn (hybrid)","YEAR":1917,"INVENTOR":"Donald F. Jones","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/sweet_corn.htm"},
{"INVENTION":"atomic transmutation","YEAR":1918,"INVENTOR":"Ernest Rutherford","COUNTRY":"United Kingdom","id":"GBR","Link":"https://en.wikipedia.org/wiki/Nuclear_transmutation"},
{"INVENTION":"mobile home","YEAR":1919,"INVENTOR":"Glenn H. Curtiss","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/mobile_homes.htm"},
{"INVENTION":"blow-dryer","YEAR":1920,"INVENTOR":"Racine Universal Motor Co., Hamilton Beach Manufacturing Co.","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/blow_dryer.htm"},
{"INVENTION":"bandage","YEAR":1921,"INVENTOR":"Earle Dickson","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/bandage.htm"},
{"INVENTION":"insulin","YEAR":1921,"INVENTOR":"Sir Frederick Grant Banting, Charles H. Best","COUNTRY":"Canada","id":"CAN","Link":"http://www.edinformatics.com/inventions_inventors/insulin.htm"},
{"INVENTION":"polygraph (lie detector)","YEAR":1921,"INVENTOR":"John A. Larson","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/polygraph.htm"},
{"INVENTION":"car radio","YEAR":1921,"INVENTOR":"William P. Lear","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/car_audio_systems.htm"},
{"INVENTION":"Muzak","YEAR":1922,"INVENTOR":"George Owen Squier","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/muzak.htm"},
{"INVENTION":"snowmobile","YEAR":1922,"INVENTOR":"Joseph-Armand Bombardier","COUNTRY":"Canada","id":"CAN","Link":"http://www.edinformatics.com/inventions_inventors/snowmobile.htm"},
{"INVENTION":"traffic lights (automatic)","YEAR":1923,"INVENTOR":"Garrett A. Morgan","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/traffic_lights.htm"},
{"INVENTION":"frozen food","YEAR":1924,"INVENTOR":"Clarence Birdseye","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/frozen_food.htm"},
{"INVENTION":"loudspeaker","YEAR":1924,"INVENTOR":"Chester W. Rice, Edward W. Kellogg","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/loudspeaker.htm"},
{"INVENTION":"aerosol can","YEAR":1926,"INVENTOR":"Erik Rotheim","COUNTRY":"Norway","id":"NOR","Link":"http://www.edinformatics.com/inventions_inventors/aerosol_can.htm"},
{"INVENTION":"rocket engine","YEAR":1926,"INVENTOR":"Robert H. Goddard","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/rocket_engine.htm"},
{"INVENTION":"baby food (prepared)","YEAR":1927,"INVENTOR":"Dorothy Gerber","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/baby_food.htm"},
{"INVENTION":"quartz clock","YEAR":1927,"INVENTOR":"Warren A. Marrison","COUNTRY":"Canada","id":"CAN","Link":"http://www.edinformatics.com/inventions_inventors/quartz_clock.htm"},
{"INVENTION":"television","YEAR":1927,"INVENTOR":"Philo Taylor Farnsworth","COUNTRY":"Russia","id":"RUS","id":"RUS","Link":"http://www.edinformatics.com/inventions_inventors/television.htm"},
{"INVENTION":"audiotape","YEAR":1928,"INVENTOR":"Fritz Pfleumer","COUNTRY":"Germany","id":"DEU","Link":"http://www.edinformatics.com/inventions_inventors/audiotape.htm"},
{"INVENTION":"bread-slicing machine","YEAR":1928,"INVENTOR":"Otto Frederick Rohwedder","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/bread-slicer.html"},
{"INVENTION":"electric razor","YEAR":1928,"INVENTOR":"Jacob Schick","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/electric_razor.htm"},
{"INVENTION":"electroencephalogram (EEG)","YEAR":1929,"INVENTOR":"Hans Berger","COUNTRY":"Germany","id":"DEU","Link":"http://www.edinformatics.com/inventions_inventors/eeg.htm"},
{"INVENTION":"jet engine","YEAR":1930,"INVENTOR":"Sir Frank Whittle","COUNTRY":"United Kingdom","id":"GBR","Link":"http://www.edinformatics.com/inventions_inventors/jet_engine.htm"},
{"INVENTION":"miniature golf","YEAR":1930,"INVENTOR":"Garnet Carter","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/miniature_golf.htm"},
{"INVENTION":"scotch tape","YEAR":1930,"INVENTOR":"Richard Drew (3M)","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/scotch_tape.htm"},
{"INVENTION":"supermarket","YEAR":1930,"INVENTOR":"Michael Cullen","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/supermarket.htm"},
{"INVENTION":"paper towel","YEAR":1931,"INVENTOR":"Arthur Scott","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/paper_towel.htm"},
{"INVENTION":"stereophonic sound recording","YEAR":1931,"INVENTOR":"Alan Dower Blumlein","COUNTRY":"United Kingdom","id":"GBR","Link":"http://www.edinformatics.com/inventions_inventors/stereophonic_sound_recording.htm"},
{"INVENTION":"tampon","YEAR":1931,"INVENTOR":"Earle Cleveland Haas","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/tampon.htm"},
{"INVENTION":"parking meter","YEAR":1932,"INVENTOR":"Carl C. Magee","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/parking_meter.htm"},
{"INVENTION":"neutron","YEAR":1932,"INVENTOR":"James Chadwick","COUNTRY":"United Kingdom","id":"GBR","Link":"https://en.wikipedia.org/wiki/Neutron"},
{"INVENTION":"particle accelerator","YEAR":1932,"INVENTOR":"John Douglas Crockcroft and Thomas Sinton Walton","COUNTRY":"United Kingdom","id":"GBR","Link":"https://en.wikipedia.org/wiki/Particle_accelerator"},
{"INVENTION":"electron microscope","YEAR":1933,"INVENTOR":"Ernst Ruska","COUNTRY":"Germany","id":"DEU","Link":"http://www.edinformatics.com/inventions_inventors/electron_microscope.htm"},
{"INVENTION":"laundromat","YEAR":1934,"INVENTOR":"J.F. Cantrell","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/laundromat.htm"},
{"INVENTION":"light bulb (fluorescent)","YEAR":1934,"INVENTOR":"Arthur Compton","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/fluorescent_lamp.htm"},
{"INVENTION":"Monopoly (board game)","YEAR":1934,"INVENTOR":"Charles B. Darrow","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/monopoly_game.htm"},
{"INVENTION":"Switching circuit theory (digital electronics)","YEAR":1934,"INVENTOR":"Akira Nakajima","COUNTRY":"Japan","id":"JPN","Link":"https://en.wikipedia.org/wiki/Digital_electronics"},
{"INVENTION":"polyethylene","YEAR":1935,"INVENTOR":"Eric Fawcett, Reginald Gibson","COUNTRY":"United Kingdom","id":"GBR","Link":"http://www.edinformatics.com/inventions_inventors/polyethylene.htm"},
{"INVENTION":"Richter scale","YEAR":1935,"INVENTOR":"Charles Francis Richter, Beno Gutenberg","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/richter_scale.htm"},
{"INVENTION":"nylon","YEAR":1937,"INVENTOR":"Wallace H. Carothers","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/nylon.htm"},
{"INVENTION":"photocopying (xerography)","YEAR":1937,"INVENTOR":"Chester F. Carlson","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/photocopying.htm"},
{"INVENTION":"fiberglass","YEAR":1938,"INVENTOR":"Owens Corning (corp.)","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/fiberglass.htm"},
{"INVENTION":"pen","YEAR":1938,"INVENTOR":"Lazlo Biro","COUNTRY":"Hungary","id":"HUN","Link":"http://www.edinformatics.com/inventions_inventors/ballpoint_pen.htm"},
{"INVENTION":"teflon","YEAR":1938,"INVENTOR":"Roy Plunkett","COUNTRY":"United States of America","id":"USA","Link":"http://www.worldofmolecules.com/materials/teflon.htm"},
{"INVENTION":"blood bank","YEAR":1939,"INVENTOR":"Charles Richard Drew","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/blood_bank.htm"},
{"INVENTION":"helicopter","YEAR":1939,"INVENTOR":"Igor Sikorsky","COUNTRY":"Russia","id":"RUS","Link":"http://www.edinformatics.com/inventions_inventors/helicopter.htm"},
{"INVENTION":"lawn mower (gasoline-powered)","YEAR":1940,"INVENTOR":"Leonard Goodall","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/lawnmower.htm"},
{"INVENTION":"electric guitar","YEAR":1941,"INVENTOR":"Les Paul","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/electric_guitar.htm"},
{"INVENTION":"guided missile","YEAR":1942,"INVENTOR":"Wernher von Braun","COUNTRY":"Germany","id":"DEU","Link":"http://www.edinformatics.com/inventions_inventors/rocket_engine.htm"},
{"INVENTION":"nuclear reactor","YEAR":1942,"INVENTOR":"Enrico Fermi","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/nuclear_reactor.htm"},
{"INVENTION":"scuba gear","YEAR":1943,"INVENTOR":"Jacques Cousteau, Camile Gagnan","COUNTRY":"France","id":"FRA","Link":"http://www.edinformatics.com/inventions_inventors/scuba_gear.htm"},
{"INVENTION":"assault rifle","YEAR":1944,"INVENTOR":"Hugo Schmeisser","COUNTRY":"Germany","id":"DEU","Link":""},
{"INVENTION":"sunscreen","YEAR":1944,"INVENTOR":"Benjamin Green","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/sunscreen.htm"},
{"INVENTION":"atomic bomb","YEAR":1945,"INVENTOR":"J. Robert Oppenheimer and others","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/atomic_bomb.htm"},
{"INVENTION":"microwave oven","YEAR":1945,"INVENTOR":"Percy L. Spencer","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/microwave_oven.htm"},
{"INVENTION":"bikini","YEAR":1946,"INVENTOR":"Louis Réard","COUNTRY":"France","id":"FRA","Link":"http://www.edinformatics.com/inventions_inventors/bikini.htm"},
{"INVENTION":"cat litter","YEAR":1947,"INVENTOR":"Edward Lowe","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/cat_litter.htm"},
{"INVENTION":"lego","YEAR":1947,"INVENTOR":"Ole Kirk Christiansen","COUNTRY":"Denmark","id":"DNK","Link":"http://www.edinformatics.com/inventions_inventors/lego.htm"},
{"INVENTION":"photography (instant)","YEAR":1947,"INVENTOR":"Edwin Herbert Land","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/instant_photography.htm"},
{"INVENTION":"transistor","YEAR":1947,"INVENTOR":"John Bardeen, Walter H. Brattain, William B. Shockley","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/transistor.htm"},
{"INVENTION":"holography","YEAR":1948,"INVENTOR":"Dennis Gabor","COUNTRY":"Hungary","id":"HUN","Link":"http://www.edinformatics.com/inventions_inventors/holography.htm"},
{"INVENTION":"record (long-playing)","YEAR":1948,"INVENTOR":"Peter Carl Goldmark","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/long_play_records.htm"},
{"INVENTION":"Velcro","YEAR":1948,"INVENTOR":"George de Mestral","COUNTRY":"Switzerland","id":"CHE","Link":"http://www.edinformatics.com/inventions_inventors/velcro.htm"},
{"INVENTION":"Zamboni (ice resurfacing machine)","YEAR":1949,"INVENTOR":"Frank J. Zamboni","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/ice_resurfacer.htm"},
{"INVENTION":"magnetic-core memory","YEAR":1949,"INVENTOR":"An Wang, Way-Dong Woo","COUNTRY":"China","id":"CHN","Link":"https://en.wikipedia.org/wiki/Magnetic-core_memory"},
{"INVENTION":"credit card","YEAR":1950,"INVENTOR":"Frank McNamara, Ralph Schneider (Diners' Club)","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/credit_card.htm"},
{"INVENTION":"remote control for television","YEAR":1950,"INVENTOR":"Robert Adler","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/remote_control.htm"},
{"INVENTION":"static induction transistor","YEAR":1950,"INVENTOR":"Jun-ichi Nishizawa, Y. Watanabe","COUNTRY":"Japan","id":"JPN","Link":"https://en.wikipedia.org/wiki/Static_induction_transistor"},
{"INVENTION":"modem","YEAR":1950,"INVENTOR":"MIT and Bell Labs","COUNTRY":"United States of America","id":"USA","Link":"https://en.wikipedia.org/wiki/Modem"},
{"INVENTION":"Karnaugh mapping technique (digital logic)","YEAR":1950,"INVENTOR":"Maurice Karnaugh","COUNTRY":"United States of America","id":"USA","Link":"https://en.wikipedia.org/wiki/Karnaugh_map"},
{"INVENTION":"magnetic disk (floppy disk)","YEAR":1950,"INVENTOR":"Yoshiro Nakamatsu","COUNTRY":"Japan","id":"JPN","Link":"https://en.wikipedia.org/wiki/Magnetic_disk"},
{"INVENTION":"correction fluid","YEAR":1951,"INVENTOR":"Bette Nesmith","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/correction_fluid.htm"},
{"INVENTION":"airbag","YEAR":1952,"INVENTOR":"John Hetrick","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/airbag.htm"},
{"INVENTION":"bar code","YEAR":1952,"INVENTOR":"Joseph Woodland","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/bar_code.htm"},
{"INVENTION":"thermonuclear bomb","YEAR":1952,"INVENTOR":"Edward Teller, et al.","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/hydrogen_bomb.htm"},
{"INVENTION":"defibrillator","YEAR":1952,"INVENTOR":"Paul M. Zoll","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/defibrillators.htm"},
{"INVENTION":"heart pacemaker","YEAR":1952,"INVENTOR":"Paul M. Zoll","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/pacemaker_cardiac.htm"},
{"INVENTION":"digital voltmeter","YEAR":1952,"INVENTOR":"Andrew F. Kay","COUNTRY":"United States of America","id":"USA","Link":"https://en.wikipedia.org/wiki/Voltmeter"},
{"INVENTION":"helical scan video tape recorder","YEAR":1953,"INVENTOR":"Dr. Norikazu Sawazaki","COUNTRY":"Japan","id":"JPN","Link":"https://en.wikipedia.org/wiki/Helical_scan"},
{"INVENTION":"transistor computer","YEAR":1953,"INVENTOR":"University of Manchester","COUNTRY":"United Kingdom","id":"GBR","Link":"https://en.wikipedia.org/wiki/Transistor_computer"},
{"INVENTION":"optical fiber","YEAR":1954,"INVENTOR":"Narinder Singh Kapany","COUNTRY":"United States of America","id":"USA","Link":"https://en.wikipedia.org/wiki/Optical_fiber"},
{"INVENTION":"solar battery","YEAR":1954,"INVENTOR":"Chapin, Fuller, and Pearson","COUNTRY":"United States of America","id":"USA","Link":""},
{"INVENTION":"parametron","YEAR":1954,"INVENTOR":"Eiichi Goto","COUNTRY":"Japan","id":"JPN","Link":"https://en.wikipedia.org/wiki/Parametron"},
{"INVENTION":"artificial diamond","YEAR":1955,"INVENTOR":"General Electric Co.","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/synthetic_diamond.htm"},
{"INVENTION":"fiber optics","YEAR":1955,"INVENTOR":"Narinder S. Kapany","COUNTRY":"India","id":"IND","Link":"http://www.edinformatics.com/inventions_inventors/fiber_optics.htm"},
{"INVENTION":"respirator","YEAR":1955,"INVENTOR":"Forrest M. Bird","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/respirator.htm"},
{"INVENTION":"synthesizer (musical instrument)","YEAR":1955,"INVENTOR":"Harry Olson, Herbert Belar","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/music_synthesizer.htm"},
{"INVENTION":"hard disk drive","YEAR":1956,"INVENTOR":"IBM","COUNTRY":"United States of America","id":"USA","Link":"https://en.wikipedia.org/wiki/Hard_disk_drive"},
{"INVENTION":"Play-Doh","YEAR":1956,"INVENTOR":"Noah W. & Joseph S. McVicker","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/play_doh.htm"},
{"INVENTION":"videotape","YEAR":1956,"INVENTOR":"Charles Ginsburg","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/videotape.htm"},
{"INVENTION":"personal computer (IBM 610)","YEAR":1957,"INVENTOR":"IBM","COUNTRY":"United States of America","id":"USA","Link":"https://en.wikipedia.org/wiki/Personal_computer"},
{"INVENTION":"electric desktop calculator (Model 14-A)","YEAR":1957,"INVENTOR":"Casio","COUNTRY":"Japan","id":"JPN","Link":"https://en.wikipedia.org/wiki/Desktop_calculator"},
{"INVENTION":"satellite (Sputnik 1)","YEAR":1957,"INVENTOR":"Kerim Kerimov","COUNTRY":"Russia","id":"RUS","Link":"https://en.wikipedia.org/wiki/Satellite"},
{"INVENTION":"nuclear missile","YEAR":1957,"INVENTOR":"Igor Kurchatov","COUNTRY":"Russia","id":"RUS","Link":"https://en.wikipedia.org/wiki/Nuclear_Missile"},
{"INVENTION":"FORTRAN programming language","YEAR":1957,"INVENTOR":"IBM","COUNTRY":"United States of America","id":"USA","Link":"https://en.wikipedia.org/wiki/Fortran"},
{"INVENTION":"integrated circuit","YEAR":1958,"INVENTOR":"Jack S. Kilby","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/integrated_circuit.htm"},
{"INVENTION":"laser","YEAR":1958,"INVENTOR":"Gordon Gould and Charles Hard Townes, Arthur L. Schawlow (invented separately)","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/laser.htm"},
{"INVENTION":"skateboard","YEAR":1958,"INVENTOR":"Bill & Mark Richards","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/skateboard.htm"},
{"INVENTION":"ultrasound imaging","YEAR":1958,"INVENTOR":"Ian Donald","COUNTRY":"United Kingdom","id":"GBR","Link":"http://www.edinformatics.com/inventions_inventors/ultrasound.htm"},
{"INVENTION":"seat-belt","YEAR":1959,"INVENTOR":"Nils Bohlin (Volvo)","COUNTRY":"Sweden","id":"SWE","Link":"http://www.edinformatics.com/inventions_inventors/seat_belt.htm"},
{"INVENTION":"first one-piece plain paper photocopier (Xerox 914)","YEAR":1959,"INVENTOR":"Xerox","COUNTRY":"United States of America","id":"USA","Link":"https://en.wikipedia.org/wiki/Photocopier"},
{"INVENTION":"communication satellite","YEAR":1960,"INVENTOR":"John Robinson Pierce","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/communication_satellite.htm"},
{"INVENTION":"the Unimate (programmable industrial robot)","YEAR":1961,"INVENTOR":"George C. Devol Jr.","COUNTRY":"United States of America","id":"USA","Link":""},
{"INVENTION":"microprogram-controlled electronic computer (KT-Pilot)","YEAR":1961,"INVENTOR":"Kyoto University, Toshiba","COUNTRY":"Japan","id":"JPN","Link":"https://en.wikipedia.org/wiki/Microprogram"},
{"INVENTION":"light-emitting diode (LED)","YEAR":1962,"INVENTOR":"Nick Holonyak, Jr.","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/light_emitting_diode.htm"},
{"INVENTION":"liquid crystal display (LCD)","YEAR":1963,"INVENTOR":"George Heilmeier","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/lcd.htm"},
{"INVENTION":"computer mouse","YEAR":1963,"INVENTOR":"Douglas Engelbart","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/computer_mouse.htm"},
{"INVENTION":"BASIC programming language","YEAR":1964,"INVENTOR":"John G. Kemeny and Thomas E. Kurtz","COUNTRY":"United States of America","id":"USA","Link":"https://en.wikipedia.org/wiki/BASIC_programming_language"},
{"INVENTION":"aspartame","YEAR":1965,"INVENTOR":"James Schlatter","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/aspartame.htm"},
{"INVENTION":"AstroTurf","YEAR":1965,"INVENTOR":"James M. Faria, Robert T. Wright","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/astroturf.htm"},
{"INVENTION":"kevlar","YEAR":1965,"INVENTOR":"Stephanie Kwolek","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/kevlar.htm"},
{"INVENTION":"DRAM memory","YEAR":1965,"INVENTOR":"Toshiba","COUNTRY":"Japan","id":"JPN","Link":"https://en.wikipedia.org/wiki/Dynamic_random-access_memory"},
{"INVENTION":"optical fiber communications","YEAR":1966,"INVENTOR":"Sir Charles Kuen Kao","COUNTRY":"United Kingdom","id":"GBR","Link":"https://en.wikipedia.org/wiki/Optical_fiber_communications"},
{"INVENTION":"calculator (electronic, hand-held)","YEAR":1967,"INVENTOR":"Jack S. Kilby","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/calculator.htm"},
{"INVENTION":"automated teller machine (ATM)","YEAR":1968,"INVENTOR":"Don Wetzel","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/automated_teller_machine.htm"},
{"INVENTION":"personal watercraft","YEAR":1968,"INVENTOR":"Bombardier, Inc.","COUNTRY":"Canada","id":"CAN","Link":"http://www.edinformatics.com/inventions_inventors/personal_watercraft.htm"},
{"INVENTION":"text-to-speech synthesis","YEAR":1968,"INVENTOR":"Noriko Umeda (Electrotechnical Laboratory)","COUNTRY":"Japan","id":"JPN","Link":"https://en.wikipedia.org/wiki/Speech_synthesis"},
{"INVENTION":"smoke detector","YEAR":1969,"INVENTOR":"Randolph Smith, Kenneth House","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/smoke_detector.htm"},
{"INVENTION":"Internet","YEAR":1969,"INVENTOR":"Advanced Research Projects Agency (ARPA) at the Dept. of Defense","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/internet.htm"},
{"INVENTION":"videocassette recorder","YEAR":1969,"INVENTOR":"Sony Corp.","COUNTRY":"Japan","id":"JPN","Link":"http://www.edinformatics.com/inventions_inventors/videocasette_recorder.htm"},
{"INVENTION":"digital fax machine","YEAR":1969,"INVENTOR":"Dacom","COUNTRY":"United States of America","id":"USA","Link":"https://en.wikipedia.org/wiki/Fax#Digital"},
{"INVENTION":"UNIX operating system","YEAR":1969,"INVENTOR":"Dennis Ritchie","COUNTRY":"United States of America","id":"USA","Link":"https://en.wikipedia.org/wiki/Unix"},
{"INVENTION":"animal cloning","YEAR":1970,"INVENTOR":"John B. Gurdon","COUNTRY":"United Kingdom","id":"GBR","Link":"http://www.edinformatics.com/inventions_inventors/animal_cloning.htm"},
{"INVENTION":"digital wristwatch","YEAR":1970,"INVENTOR":"John M. Bergey","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/digital_watch.htm"},
{"INVENTION":"Commercial DRAM memory","YEAR":1970,"INVENTOR":"IBM","COUNTRY":"United States of America","id":"USA","Link":"https://en.wikipedia.org/wiki/Dynamic_random-access_memory"},
{"INVENTION":"microprocessor Intel 4004 (for PC)","YEAR":1971,"INVENTOR":"Intel","COUNTRY":"United States of America","id":"USA","Link":"https://en.wikipedia.org/wiki/Microprocessor"},
{"INVENTION":"electronic mail (e-mail)","YEAR":1971,"INVENTOR":"Ray Tomlinson","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/email.htm"},
{"INVENTION":"food processor","YEAR":1971,"INVENTOR":"Pierre Verdon","COUNTRY":"France","id":"FRA","Link":"http://www.edinformatics.com/inventions_inventors/food_processor.htm"},
{"INVENTION":"space station (Salyut 1)","YEAR":1971,"INVENTOR":"Kerim Kerimov","COUNTRY":"Russia","id":"RUS","Link":"https://en.wikipedia.org/wiki/Space_station"},
{"INVENTION":"EPROM","YEAR":1971,"INVENTOR":"Dov Frohman","COUNTRY":"Netherlands","id":"NLD","Link":"https://en.wikipedia.org/wiki/EPROM"},
{"INVENTION":"arcade video game (Computer Space)","YEAR":1971,"INVENTOR":"Nolan Bushnell, Ted Dabney","COUNTRY":"United States of America","id":"USA","Link":"https://en.wikipedia.org/wiki/Arcade_video_game"},
{"INVENTION":"PASCAL programming language","YEAR":1971,"INVENTOR":"Niklaus E. Wirth ","COUNTRY":"Switzerland","id":"CHE","Link":"https://en.wikipedia.org/wiki/Pascal_(programming_language)"},
{"INVENTION":"microcontroller","YEAR":1971,"INVENTOR":"Texas Instruments","COUNTRY":"United States of America","id":"USA","Link":"https://en.wikipedia.org/wiki/Microcontroller"},
{"INVENTION":"laser printer","YEAR":1971,"INVENTOR":"Xerox","COUNTRY":"United States of America","id":"USA","Link":"https://en.wikipedia.org/wiki/Laser_printer"},
{"INVENTION":"computed tomography (CT scan, CAT scan)","YEAR":1972,"INVENTOR":"Godfrey Hounsfield, Allan Cormack","COUNTRY":"United Kingdom","id":"GBR","Link":"http://www.edinformatics.com/inventions_inventors/cat_scans.htm"},
{"INVENTION":"magnetic resonance imaging (MRI)","YEAR":1972,"INVENTOR":"Raymond Damadian, Paul Lauterbur","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/mri.htm"},
{"INVENTION":"Prozac","YEAR":1972,"INVENTOR":"Ray W. Fuller, Bryan B. Molloy, David T. Wong","COUNTRY":"United States of America","id":"USA","Link":"http://www.worldofmolecules.com/drugs/prozac.htm"},
{"INVENTION":"video games","YEAR":1972,"INVENTOR":"Nolan Bushnell","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/video_games.htm"},
{"INVENTION":"8008 processor (200 kHz, 16 kB)","YEAR":1972,"INVENTOR":"Intel","COUNTRY":"United States of America","id":"USA","Link":"https://en.wikipedia.org/wiki/Intel_8008"},
{"INVENTION":"handheld electronic game (Electro Tic-Tac-Toe)","YEAR":1972,"INVENTOR":"Waco","COUNTRY":"Japan","id":"JPN","Link":"https://en.wikipedia.org/wiki/Handheld_electronic_game"},
{"INVENTION":"Video game console (Magnavox Odyssey)","YEAR":1972,"INVENTOR":"Ralph Baer (Magnavox)","COUNTRY":"United States of America","id":"USA","Link":"https://en.wikipedia.org/wiki/Video_game_console"},
{"INVENTION":"modern ATM machine (IBM 2984)","YEAR":1972,"INVENTOR":"IBM","COUNTRY":"United States of America","id":"USA","Link":"https://en.wikipedia.org/wiki/Automated_teller_machine"},
{"INVENTION":"capacitive touchscreen","YEAR":1973,"INVENTOR":"CERN","COUNTRY":"Switzerland","id":"CHE","Link":"https://en.wikipedia.org/wiki/Touchscreen#Capacitive"},
{"INVENTION":"genetic engineering","YEAR":1973,"INVENTOR":"Stanley N. Cohen, Herbert W. Boyer","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/genetic_engineering.htm"},
{"INVENTION":"color video game (Playtron)","YEAR":1973,"INVENTOR":"Kasco (Kansei Seiki Seisakusho Co.)","COUNTRY":"Japan","id":"JPN","Link":"https://en.wikipedia.org/wiki/Video_game"},
{"INVENTION":"Josephson junction","YEAR":1973,"INVENTOR":"IBM","COUNTRY":"United States of America","id":"USA","Link":"https://en.wikipedia.org/wiki/Josephson_junction"},
{"INVENTION":"tunable continuous-wave laser","YEAR":1973,"INVENTOR":"Bell Labs","COUNTRY":"United States of America","id":"USA","Link":"https://en.wikipedia.org/wiki/Tunable_laser"},
{"INVENTION":"Ethernet","YEAR":1973,"INVENTOR":"Robert Melancton ","COUNTRY":"United States of America","id":"USA","Link":"https://en.wikipedia.org/wiki/Ethernet"},
{"INVENTION":"mobile phone","YEAR":1973,"INVENTOR":"John F. Mitchell and Dr. Martin Cooper of Motorola","COUNTRY":"United States of America","id":"USA","Link":"https://en.wikipedia.org/wiki/Mobile_phone"},
{"INVENTION":"Internet protocols","YEAR":1974,"INVENTOR":"Vinton Cerf & Robert E. Kahn (DARPA)","COUNTRY":"United States of America","id":"USA","Link":"https://en.wikipedia.org/wiki/Internet_protocol_suite"},
{"INVENTION":"scrolling video game (Speed Race)","YEAR":1974,"INVENTOR":"Tomohiro Nishikado","COUNTRY":"Japan","id":"JPN","Link":"https://en.wikipedia.org/wiki/Scrolling"},
{"INVENTION":"Intel 8080 processor","YEAR":1974,"INVENTOR":"Intel","COUNTRY":"United States of America","id":"USA","Link":"https://en.wikipedia.org/wiki/Intel_8080"},
{"INVENTION":"C (programming language)","YEAR":1974,"INVENTOR":"Dennis Ritchie","COUNTRY":"United States of America","id":"USA","Link":"https://en.wikipedia.org/wiki/C_(programming_language)"},
{"INVENTION":"static induction thyristor","YEAR":1975,"INVENTOR":"Jun-ichi Nishizawa","COUNTRY":"Japan","id":"JPN","Link":"https://en.wikipedia.org/wiki/Static_induction_thyristor"},
{"INVENTION":"digital camera","YEAR":1975,"INVENTOR":"Steven Sasson of Eastman Kodak","COUNTRY":"United States of America","id":"USA","Link":"https://en.wikipedia.org/wiki/Digital_camera"},
{"INVENTION":"Zilog Z80 processor","YEAR":1976,"INVENTOR":"Zilog","COUNTRY":"United States of America","id":"USA","Link":"https://en.wikipedia.org/wiki/Zilog_Z80"},
{"INVENTION":"Apple I computer","YEAR":1976,"INVENTOR":"Steve Jobs, Steve Wozniak","COUNTRY":"United States of America","id":"USA","Link":"https://en.wikipedia.org/wiki/Apple_I"},
{"INVENTION":"x86 processor architecture (Intel 8086)","YEAR":1978,"INVENTOR":"Intel","COUNTRY":"United States of America","id":"USA","Link":"https://en.wikipedia.org/wiki/X86"},
{"INVENTION":"stereo (radio)","YEAR":1979,"INVENTOR":"Sony Corp.","COUNTRY":"Japan","id":"JPN","Link":"http://www.edinformatics.com/inventions_inventors/personal_stereo.htm"},
{"INVENTION":"graphics processing unit (NEC µPD7220)","YEAR":1979,"INVENTOR":"NEC","COUNTRY":"Japan","id":"JPN","Link":"https://en.wikipedia.org/wiki/Graphics_processing_unit"},
{"INVENTION":"flash memory","YEAR":1980,"INVENTOR":"Dr. Fujio Masuoka (Toshiba)","COUNTRY":"Japan","id":"JPN","Link":"https://en.wikipedia.org/wiki/Flash_memory"},
{"INVENTION":"compact disc (CD)","YEAR":1980,"INVENTOR":"Philips Electronics, Sony Corp.","COUNTRY":"Netherlands, Japan","id":"JPN","Link":"http://www.edinformatics.com/inventions_inventors/compact_disc.htm"},
{"INVENTION":"3½-inch floppy (2-sided, 875 kB)","YEAR":1980,"INVENTOR":"Sony","COUNTRY":"Japan","id":"JPN","Link":""},
{"INVENTION":"Compact Disc Digital Audio (Red Book)","YEAR":1980,"INVENTOR":"Sony, Philips","COUNTRY":"Japan","id":"JPN","Link":"https://en.wikipedia.org/wiki/Compact_Disc_Digital_Audio"},
{"INVENTION":"synthetic skin","YEAR":1981,"INVENTOR":"Ioannis V. Yannas, John F. Burke","COUNTRY":"United States of America","id":"USA","Link":""},
{"INVENTION":"IBM Personal Computer (8088 processor)","YEAR":1981,"INVENTOR":"IBM","COUNTRY":"United States of America","id":"USA","Link":"https://en.wikipedia.org/wiki/IBM_Personal_Computer"},
{"INVENTION":"MS-DOS 1.0","YEAR":1981,"INVENTOR":"Microsoft","COUNTRY":"United States of America","id":"USA","Link":"https://en.wikipedia.org/wiki/MS-DOS"},
{"INVENTION":"camcorder","YEAR":1982,"INVENTOR":"Sony Corp.","COUNTRY":"Japan","id":"JPN","Link":"http://www.edinformatics.com/inventions_inventors/digital_camcorder.htm"},
{"INVENTION":"CD-ROM","YEAR":1982,"INVENTOR":"Sony","COUNTRY":"Japan","id":"JPN","Link":"https://en.wikipedia.org/wiki/CD-ROM"},
{"INVENTION":"laptop","YEAR":1983,"INVENTOR":"Radio Shack Corp.","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/computers.htm"},
{"INVENTION":"satellite television","YEAR":1983,"INVENTOR":"U.S. Satellite Communications, Inc.","COUNTRY":"United States of America","id":"USA","Link":"https://en.wikipedia.org/wiki/Satellite_television"},
{"INVENTION":"C++ (programming language)","YEAR":1983,"INVENTOR":"Bjarne Stroustrup","COUNTRY":"Denmark","id":"DNK","Link":"https://en.wikipedia.org/wiki/C%2B%2B"},
{"INVENTION":"cellphone","YEAR":1984,"INVENTOR":"Motorola","COUNTRY":"United States of America","id":"USA","Link":"https://en.wikipedia.org/wiki/Cell_phone"},
{"INVENTION":"DNA fingerprinting","YEAR":1984,"INVENTOR":"Alec Jeffreys","COUNTRY":"United Kingdom","id":"GBR","Link":"http://www.edinformatics.com/inventions_inventors/dna_fingerprinting.htm"},
{"INVENTION":"LaserDisc digital data storage device","YEAR":1984,"INVENTOR":"Sony","COUNTRY":"Japan","id":"JPN","Link":"https://en.wikipedia.org/wiki/LaserDisc"},
{"INVENTION":"Macintosh computer (introduced)","YEAR":1984,"INVENTOR":"Apple Computer","COUNTRY":"United States of America","id":"USA","Link":"https://en.wikipedia.org/wiki/Macintosh"},
{"INVENTION":"laser vision correction","YEAR":1987,"INVENTOR":"Stephen Trokel","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/vision_laser_surgery.htm"},
{"INVENTION":"Warmer superconductivity","YEAR":1987,"INVENTOR":"Karl Alex Mueller","COUNTRY":"Switzerland","id":"CHE","Link":"https://en.wikipedia.org/wiki/Superconductivity"},
{"INVENTION":"80386 microprocessor (25 MHz)","YEAR":1987,"INVENTOR":"Intel","COUNTRY":"United States of America","id":"USA","Link":"https://en.wikipedia.org/wiki/Intel_80386"},
{"INVENTION":"virtual reality","YEAR":1989,"INVENTOR":"Jaron Lanier","COUNTRY":"United States of America","id":"USA","Link":"http://www.edinformatics.com/inventions_inventors/virtual_reality.htm"},
{"INVENTION":"World Wide Web (HTML)","YEAR":1989,"INVENTOR":"Tim Berners-Lee","COUNTRY":"United Kingdom","id":"GBR","Link":"http://www.edinformatics.com/inventions_inventors/www.htm"},
{"INVENTION":"commercial handheld GPS receiver (Magellan NAV 1000)","YEAR":1989,"INVENTOR":"Magellan Navigation Inc.","COUNTRY":"United States of America","id":"USA","Link":"https://en.wikipedia.org/wiki/GPS_navigation_device"},
{"INVENTION":"silicon-germanium transistors","YEAR":1989,"INVENTOR":"IBM fellow Bernie Meyerson","COUNTRY":"United States of America","id":"USA","Link":"https://en.wikipedia.org/wiki/Silicon-germanium"},
{"INVENTION":"486 microprocessor (33 MHz)","YEAR":1990,"INVENTOR":"Intel","COUNTRY":"United States of America","id":"USA","Link":"https://en.wikipedia.org/wiki/Intel_80486"},
{"INVENTION":"LINUX","YEAR":1991,"INVENTOR":"Linus Torvalds","COUNTRY":"Finland","id":"FIN","Link":"https://en.wikipedia.org/wiki/Linux"},
{"INVENTION":"Weather Control Device / HAARP","YEAR":1993,"INVENTOR":"U.S.","COUNTRY":"United States of America","id":"USA","Link":"https://en.wikipedia.org/wiki/HAARP"},
{"INVENTION":"Pentium processor, P5-based (60/90 MHz, 166.2 MIPS)","YEAR":1994,"INVENTOR":"Vinod Dham (Intel)","COUNTRY":"United States of America","id":"USA","Link":"https://en.wikipedia.org/wiki/Pentium"},
{"INVENTION":"Bluetooth","YEAR":1994,"INVENTOR":"Ericsson","COUNTRY":"Sweden","id":"SWE","Link":"https://en.wikipedia.org/wiki/Bluetooth"},
{"INVENTION":"DVD","YEAR":1994,"INVENTOR":"Sony, Panasonic, Philips, Toshiba","COUNTRY":"Japan, United States of America, Netherlands","id":"JPN","Link":"https://en.wikipedia.org/wiki/DVD"},
{"INVENTION":"DVD player","YEAR":1994,"INVENTOR":"Tatung Company, Sony","COUNTRY":"Japan","id":"JPN","Link":"https://en.wikipedia.org/wiki/DVD_player"},
{"INVENTION":"Playstation","YEAR":1994,"INVENTOR":"Sony","COUNTRY":"Japan","id":"JPN","Link":"https://en.wikipedia.org/wiki/PlayStation"},
{"INVENTION":"WINDOWS 95 operating system","YEAR":1995,"INVENTOR":"Windows","COUNTRY":"United States of America","id":"USA","Link":"https://en.wikipedia.org/wiki/Windows_95"},
{"INVENTION":"P2SC processor (15 million transistors)","YEAR":1996,"INVENTOR":"IBM","COUNTRY":"United States of America","id":"USA","Link":"https://en.wikipedia.org/wiki/POWER2#P2SC"},
{"INVENTION":"Toyota Prius (hybrid car)","YEAR":1997,"INVENTOR":"Toyota","COUNTRY":"Japan","id":"JPN","Link":"https://en.wikipedia.org/wiki/Toyota_Prius"},
{"INVENTION":"Wireless Internet","YEAR":1997,"INVENTOR":"Alex Hills","COUNTRY":"United States of America","id":"USA","Link":"https://en.wikipedia.org/wiki/Wi-Fi"},
{"INVENTION":"gas powered fuel cell","YEAR":1997,"INVENTOR":"U.S. Department of Energy (Arthur D. Little)","COUNTRY":"United States of America","id":"USA","Link":"https://en.wikipedia.org/wiki/Fuel_cell"},
{"INVENTION":"MP3 player","YEAR":1998,"INVENTOR":"Saehan","COUNTRY":"Korea","id":"KOR","Link":"https://en.wikipedia.org/wiki/MP3_player"},
{"INVENTION":"USB flash drive","YEAR":2000,"INVENTOR":"IBM","COUNTRY":"United States of America","id":"USA","Link":"https://en.wikipedia.org/wiki/USB_flash_drive#History"}];